### ISSUE TITLE
Mutant Apes Serum Type

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/metadata#14]
We want to different Mutant Apes based on their Serum type. We should be able to parse it out of the attributes. We want to do 2 things:

- Add a new `Serum Type` trait
- Update the name. If there is a name trait, use that (e.g. Mega Trippy), otherwise do `#{tokenId} ({serumType})` e.g. #123 (M1)

**Comment by ptrwtts** [comment]
Working great! Can I get two minor tweaks?

- Make the Serum Type the highest rank attribute
- Rename "M3" type to "Mega"

**Comment by georgeroman** [comment]
Done, OpenSea metadata endpoint are down but will trigger a refresh once they come back up.
