### ISSUE TITLE
Bug: Multiple collections with the same slug

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/metadata#9]
We currently have lots of collections with the same slug, because we use the contract name in the event of collection data being available on Open Sea:

https://github.com/reservoirprotocol/metadata/blob/main/pages/api/v3/mainnet/collection.js#L55

We should stop doing this, and instead set the slug to null if collection data is not available, and trigger a job to try again later.

Once we make this change, we should do a backfill on all collections to clean up the incorrect slugs we have.

**Comment by ipeleg** [comment]
Update as implemented and resync of all collections slugs was preformed
